platform :macos, '10.9'

inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs.git'


target 'iBeaconDevice' do
  pod 'DispatchTimer'
end